### ISSUE TITLE
1.18.2 No information on Curseforge or Github on how to charge the electric magnet or net launcher.

### ISSUE THREAD

**Issue by masetrhitman** [pauljoda/Assisted-Progression#1]
There appears to be no information anywhere on how to charge the Net Launcher or Advanced Magnet. The Github page doesn't even appear to acknowledge the existence of the net launcher. Is another mod required to provide power? Which power type is it looking for (I know of at least 3, and they aren't intercompatible.)? Why do I have to add an issue page to the Github for this mod for a question that should be really easy to answer? Did everybody assume that Assisted Progression would always be used in tandem with a mod that has a power system? 

I've created my own modpack, before anyone asks why my modpack doesn't have any electricity mods in it.

**Comment by pauljoda** [comment]
Items that use energy use forge energy, this is the standard and will work with many mods, such as Mekanism, DireWolf's charging gadgets etc. This is a simple mod made in my spare time, if the documentation is not clear feel free to edit the page to add information you feel may be useful on the Wiki page of this project
